// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: protos/person.proto

package people

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type USAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Street  string `protobuf:"bytes,1,opt,name=Street,proto3" json:"Street,omitempty"`
	Zipcode int32  `protobuf:"varint,2,opt,name=Zipcode,proto3" json:"Zipcode,omitempty"`
	UnitNum string `protobuf:"bytes,3,opt,name=UnitNum,proto3" json:"UnitNum,omitempty"`
	City    string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	State   string `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *USAddress) Reset() {
	*x = USAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *USAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USAddress) ProtoMessage() {}

func (x *USAddress) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USAddress.ProtoReflect.Descriptor instead.
func (*USAddress) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{0}
}

func (x *USAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *USAddress) GetZipcode() int32 {
	if x != nil {
		return x.Zipcode
	}
	return 0
}

func (x *USAddress) GetUnitNum() string {
	if x != nil {
		return x.UnitNum
	}
	return ""
}

func (x *USAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *USAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode string `protobuf:"bytes,1,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	Number      string `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneNumber) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type PhoneNumbers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cell *PhoneNumber `protobuf:"bytes,1,opt,name=Cell,proto3" json:"Cell,omitempty"`
	Home *PhoneNumber `protobuf:"bytes,2,opt,name=Home,proto3" json:"Home,omitempty"`
	Work *PhoneNumber `protobuf:"bytes,3,opt,name=Work,proto3" json:"Work,omitempty"`
}

func (x *PhoneNumbers) Reset() {
	*x = PhoneNumbers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhoneNumbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumbers) ProtoMessage() {}

func (x *PhoneNumbers) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumbers.ProtoReflect.Descriptor instead.
func (*PhoneNumbers) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{2}
}

func (x *PhoneNumbers) GetCell() *PhoneNumber {
	if x != nil {
		return x.Cell
	}
	return nil
}

func (x *PhoneNumbers) GetHome() *PhoneNumber {
	if x != nil {
		return x.Home
	}
	return nil
}

func (x *PhoneNumbers) GetWork() *PhoneNumber {
	if x != nil {
		return x.Work
	}
	return nil
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64         `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	BirthDate      string        `protobuf:"bytes,3,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Age            int32         `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	ContactNumbers *PhoneNumbers `protobuf:"bytes,5,opt,name=ContactNumbers,proto3" json:"ContactNumbers,omitempty"`
	Address        *USAddress    `protobuf:"bytes,6,opt,name=Address,proto3" json:"Address,omitempty"`
	Company        string        `protobuf:"bytes,7,opt,name=Company,proto3" json:"Company,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{3}
}

func (x *Person) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetContactNumbers() *PhoneNumbers {
	if x != nil {
		return x.ContactNumbers
	}
	return nil
}

func (x *Person) GetAddress() *USAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Person) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

// generic response for error/completion/etc... messages beyond rpc protocols
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespMessage string `protobuf:"bytes,1,opt,name=RespMessage,proto3" json:"RespMessage,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetRespMessage() string {
	if x != nil {
		return x.RespMessage
	}
	return ""
}

type PersonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PersonReq) Reset() {
	*x = PersonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_person_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonReq) ProtoMessage() {}

func (x *PersonReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_person_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonReq.ProtoReflect.Descriptor instead.
func (*PersonReq) Descriptor() ([]byte, []int) {
	return file_protos_person_proto_rawDescGZIP(), []int{5}
}

func (x *PersonReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_protos_person_proto protoreflect.FileDescriptor

var file_protos_person_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x55, 0x53, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x5a, 0x69,
	0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x5a, 0x69, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x6e, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55, 0x6e, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x43, 0x65, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x43, 0x65,
	0x6c, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x48, 0x6f,
	0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x57, 0x6f,
	0x72, 0x6b, 0x22, 0xef, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x67,
	0x65, 0x12, 0x43, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x61, 0x66, 0x6b,
	0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f,
	0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x55, 0x53, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x22, 0x2c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x1b, 0x0a, 0x09, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x32,
	0x4a, 0x0a, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x6b, 0x61, 0x66, 0x6b,
	0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x1a, 0x17, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e,
	0x2f, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x3b, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_person_proto_rawDescOnce sync.Once
	file_protos_person_proto_rawDescData = file_protos_person_proto_rawDesc
)

func file_protos_person_proto_rawDescGZIP() []byte {
	file_protos_person_proto_rawDescOnce.Do(func() {
		file_protos_person_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_person_proto_rawDescData)
	})
	return file_protos_person_proto_rawDescData
}

var file_protos_person_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_person_proto_goTypes = []interface{}{
	(*USAddress)(nil),    // 0: kafka_testing.USAddress
	(*PhoneNumber)(nil),  // 1: kafka_testing.PhoneNumber
	(*PhoneNumbers)(nil), // 2: kafka_testing.PhoneNumbers
	(*Person)(nil),       // 3: kafka_testing.Person
	(*Response)(nil),     // 4: kafka_testing.Response
	(*PersonReq)(nil),    // 5: kafka_testing.PersonReq
}
var file_protos_person_proto_depIdxs = []int32{
	1, // 0: kafka_testing.PhoneNumbers.Cell:type_name -> kafka_testing.PhoneNumber
	1, // 1: kafka_testing.PhoneNumbers.Home:type_name -> kafka_testing.PhoneNumber
	1, // 2: kafka_testing.PhoneNumbers.Work:type_name -> kafka_testing.PhoneNumber
	2, // 3: kafka_testing.Person.ContactNumbers:type_name -> kafka_testing.PhoneNumbers
	0, // 4: kafka_testing.Person.Address:type_name -> kafka_testing.USAddress
	3, // 5: kafka_testing.People.CreatePerson:input_type -> kafka_testing.Person
	4, // 6: kafka_testing.People.CreatePerson:output_type -> kafka_testing.Response
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_person_proto_init() }
func file_protos_person_proto_init() {
	if File_protos_person_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_person_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*USAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhoneNumbers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_person_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_person_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_person_proto_goTypes,
		DependencyIndexes: file_protos_person_proto_depIdxs,
		MessageInfos:      file_protos_person_proto_msgTypes,
	}.Build()
	File_protos_person_proto = out.File
	file_protos_person_proto_rawDesc = nil
	file_protos_person_proto_goTypes = nil
	file_protos_person_proto_depIdxs = nil
}
