# syntax=docker/dockerfile:1

FROM golang:1.20

# Set destination for COPY
WORKDIR /build

# Download modules
COPY . ./
RUN go mod download

# Build
go build /kafka_testing

# Communicaition port
EXPOSE 8080

# Run
CMD ["/kafka_testing"]


